name: test

on:
  push:
    branches:
      - 'main'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Version
        run: |
          git config --global user.email "forehalo@gmail.com"
          git config --global user.name "forehalo"
          yarn lerna version --conventional-commits -y --no-push